model_name: "ai4bharat/indictrans2-en-indic-1B"
model_type: "indic2"
src_lang: "eng_Latn"
tgt_lang: "kas_Arab"
source_prefix: "eng_Latn kas_Arab "
use_indic_processor: true
output_dir: "outputs/models/indic2-final"

data_dir: "data"
train_file: "data/train.csv"
val_file: "data/val.csv"
test_file: "data/test.csv"
source_column: "english_text"
target_column: "kashmiri_text"

max_source_length: 128
max_target_length: 128

per_device_train_batch_size: 2
per_device_eval_batch_size: 2
gradient_accumulation_steps: 8
attn_implementation: "sdpa"
learning_rate: 0.0002
warmup_steps: 500
num_train_epochs: 1
weight_decay: 0.01
logging_steps: 100
eval_steps: 1000
save_steps: 1000
eval_max_samples: 500
save_total_limit: 5
gradient_checkpointing: true
optim: "adamw_torch"
fp16: true
predict_with_generate: true
seed: 42
num_proc: 4
cache_dir: "outputs/cache"
dataloader_num_workers: 2
torch_compile: false

use_lora: true
lora_r: 32
lora_alpha: 64
lora_dropout: 0.05
lora_target_modules: ["qkv_proj", "out_proj", "q_proj", "v_proj", "k_proj", "fc1", "fc2"]
merge_lora: true

num_beams: 8
length_penalty: 0.6
no_repeat_ngram_size: 3
max_generate_tokens: 128
batch_size: 16
mbr: false
mbr_n_best: 8
mbr_metric: "geo"
mbr_max_checkpoints: 3
top_p: 0.9
temperature: 0.7
backup_hf_repo: ""
